buckets/routes.py
from datetime import date, timedelta, datetime
from buckets import db
from buckets.forms import ExpenseForm, LoginForm, TransactForm
from buckets.models import Budget, User, Transactions
from flask import (
    Blueprint, flash, redirect, render_template, request,
    session, url_for, json)
from flask_login import current_user, login_required


bp = Blueprint("routes", __name__)

@bp.route("/")
@bp.route("/index") #this will be used for the home page

def index():

    return render_template('index.html', title='Home')

# the below routes are all dealing with the main budget display and creating and editing the budget expenses to track

@bp.route("/budget/", defaults={'continue_flag': 'No' }, methods=['GET', 'POST'])
@bp.route("/budget/<string:continue_flag>", methods=['GET', 'POST'])
@login_required
def disp_budget(continue_flag):
    form = ExpenseForm()
    form2 = TransactForm()
    expenses = Budget.query.filter_by(username=current_user.username).all()

    displayfields = ['group', 'expense', 'amount', 'last_paid', 'expense_cycle', 'available', 'est_min']
    buttonName = 'Add New Budget Expense'
    columns = [
        {'name':'Group','sortable':"true"},
        {'name':'Expense','sortable':"true"},
        {'name':'Amount','sortable':"true"},
        {'name':'Last Paid','sortable':"true"},
        {'name':'Expense Cycle','sortable':"false"},
        {'name':'Available','sortable':"false"},
        {'name':'Estimated Min','sortable':"false"},
        {'name':'Edit','sortable':"false"},
        {'name':'Delete','sortable':"false"}]
    rows = []
    for expense in expenses:
        expensedict = {'id':expense.id, 'username':expense.username, 'group':expense.group, 'expense':expense.expense,
        'amount':"{:.2f}".format(expense.amount), 'last_paid':expense.last_paid.strftime('%Y-%m-%d'), 'expense_cycle':expense.expense_cycle,
        'available':expense.available, 'est_min':expense.est_min
        }
        rows.append(expensedict)

    #dont forget to update routes below when making new ones!
    return render_template('/budget/index.html', title='Budget', form=form, form2=form2, columns=columns, rows=rows, fields=displayfields,
        create_route='bp.create_expense', update_route='bp.update_expense', payday_route='bp.pay_day', self_route='bp.disp_budget', buttonName=buttonName, continue_flag=continue_flag)

@login_required
@bp.route("/budget/payday/", methods=['GET', 'POST'])
def pay_day():
        # initial 
        # set pay_day = userset date
        # if payday-today >=7 then Add expense/expensecycle to available
        # payday=today write a new last paid date
    expenses = Budget.query.filter_by(username=current_user.username).all()

    for expense in expenses:
        expense.available = expense.available + expense.amount
        expense.in_flows = expense.in_flows + expense.amount
    db.session.commit()
    flash('You got paid!')
    return redirect(url_for('routes.disp_budget'))

@login_required
@bp.route("/budget/cancel/", methods=['GET', 'POST'])
def cancel_pay():
        # initial 
        # set pay_day = userset date
        # if payday-today >=7 then Add expense/expensecycle to available
        # payday=today write a new last paid date
    expenses = Budget.query.filter_by(username=current_user.username).all()

    for expense in expenses:
        expense.available = expense.available - expense.amount
        expense.inflows = expense.in_flows - expense.amount
    db.session.commit()
    flash('Reversed Pay Week')
    return redirect(url_for('routes.disp_budget'))

@login_required
def delete_expense(expense_id):
    expense = Budget.query.get_or_404(expense_id)
    if expense.username != current_user.username:
        abort(403)
    db.session.delete(expense)
    db.session.commit()
    flash('Your expense has been deleted!', 'success')
    return redirect(url_for('routes.disp_budget'))

@bp.route("/budget/create/<string:continue_flag>", methods=['GET', 'POST'])
@login_required
def create_expense(continue_flag):
    form = ExpenseForm()
    today = date.today()
    print(today)
    if form.validate_on_submit():
        #the next block is to determine the variables for the total amount required in the available bucket 
        testcycle = form.cycle.data
        amount = form.amount.data  
        option_select = form.nxtlst_select.data

        #convert the string selection into a value used in the formula to calculate the split cost per week
        if testcycle == 'Weekly':
            value = 1
            datevalue = timedelta(weeks=+1)
        elif testcycle == 'Fortnightly':
            value = 2
            datevalue = timedelta(weeks=+2)
        elif testcycle == 'Monthly':
            value = 4
            datevalue = timedelta(months=+1)
        elif testcycle == 'Yearly':
            value = 52
            datevalue = timedelta(years=+1)
        #use the selected value of either a last paid or next due for the expense to determine the date data      
        if option_select == 'lp':
            last_paid = form.last_paid.data
            next_due = last_paid + datevalue
            datedif = today-last_paid
            available = amount/value*int((datedif.days)/7)
            est_min = amount/value*int((datedif.days)/7)
        elif option_select == 'nd':
            next_due = form.last_paid.data
            last_paid = next_due - datevalue
            datedif = next_due-today
            available = amount/int((datedif.days)/7)
            est_min = amount/int((datedif.days)/7)
        #write form data to database
        #set starting values for inflows, outflows
        in_flows = 0
        out_flows = 0
        Expense = Budget(group=form.group.data, expense=form.expense.data, amount=amount, last_paid=last_paid, next_due=next_due,
        username=current_user.username, expense_cycle=form.cycle.data, available=available, est_min=est_min, in_flows=in_flows, out_flows=out_flows)
        db.session.add(Expense)
        db.session.commit() 
        flash('Your expense has been created!', 'success')
        return redirect(url_for('routes.disp_budget', username=current_user.username, continue_flag=continue_flag))
    flash(form.errors)
    return redirect(url_for('routes.disp_budget', username=current_user.username, continue_flag=continue_flag))

@bp.route("/budget/update/<int:expense_id>", methods=['GET', 'POST'])
@login_required
def update_expense(expense_id):
    expense = Budget.query.get_or_404(expense_id)
    if expense.username != current_user.username:
        abort(403)
    form = ExpenseForm()
    if form.validate_on_submit():
        today = date.today()
        form.nxtlst_select == 'lp'
        last_paid = form.last_paid.data
        amount = form.amount.data
        cycle = form.cycle.data
        expense.group = form.group.data
        expense.amount = amount
        expense.expense = form.expense.data
        expense.available = request.form['avail']
        expense.last_paid = last_paid
        expense.expense_cycle = cycle
        #convert the string selection into a value used in the formula to calculate the split cost per week
        if cycle == 'Weekly':
            value = 1
        elif cycle == 'Fortnightly':
            value = 2
        elif cycle == 'Monthly':
            value = 4
        elif cycle == 'Yearly':
            value = 52
        datedif = today-last_paid
        #need error checking to prevent dates greater than today
        expense.est_min = amount/value*int((datedif.days)/7)
        db.session.commit()
        flash('Your expense has been updated!', 'success')
        return redirect(url_for('routes.disp_budget'))
    flash(form.errors)
    return redirect(url_for('routes.disp_budget', expense_id=expense_id))

@bp.route("/budget/delete/<int:expense_id>", methods=['GET', 'POST'])
@login_required
def delete_expense(expense_id):
    expense = Budget.query.get_or_404(expense_id)
    if expense.username != current_user.username:
        flash(errors)
        abort(403)
    db.session.delete(expense)
    db.session.commit()
    flash('Your expense has been deleted!', 'success')
    return redirect(url_for('routes.disp_budget'))

@bp.route("/budget/deleteall/", methods=['GET', 'POST'])
@login_required
def deleteall():
    Budget.query.filter_by(username=current_user.username).delete()
    db.session.commit()
    flash('Expenses Reset', 'success')
    return redirect(url_for('routes.disp_budget'))




buckets/templates/budget/create.html
<!-- Add Expense Modal Budget -->
    <div class="modal fade" id="AddNewModal" tabindex="-1" role="dialog" aria-labelledby="AddNewModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="AddNewModalLabel">Create Expense</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
        <form action="{{ url_for('routes.create_expense', continue_flag=continue_flag) }}" method="post">
            {{ form.hidden_tag() }}
            <p>
                {{ form.group.label }}<br>
                {{ form.group }}<br>
                {% for error in form.group.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.expense.label }}<br>
                {{ form.expense }}<br>
                {% for error in form.expense.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.amount.label }}<br>
                {{ form.amount }}<br>
                {% for error in form.amount.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                <br>
                {{ form.nxtlst_select }}
                <br>
                {% for error in form.nxtlst_select.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.last_paid(type="date") }}
                {% for error in form.last_paid.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                <label class="mr-sm-2" for="inlineFormCustomSelect">{{ form.cycle.label }}</label>
                <br>
                {{ form.cycle }}
                <br>
                {% for error in form.cycle.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            
            <p>{{ form.submit(hidden='true', id='form-submit') }}</p>
        </form>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
        <button type="submit" class="btn btn-primary" id="modal-create">Add Expense</button>
        </div>
    </div>
    </div>
</div>
<script>

    $('#modal-create').click(function(){
        // Perform the action after modal confirm button is clicked.
    
        $('#form-submit').click(); // submitting the form
    }); 
</script>
{% if form.errors %}
<script>
$('#AddNewModal').modal('show');

</script>

{% endif %}

buckets/templates/budget/delete.html

<!-- Delete Expense Modal -->
<div class="modal fade" id="deleteModal{{ row.id }}" tabindex="-1" role="dialog" aria-labelledby="DeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Expense</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-footer">
            <form action="{{ url_for('routes.delete_expense', expense_id=row.id) }}" method="POST">
               <button type="submit" class="btn btn-primary" id="modal-test", value="Delete">Delete Expense</button> 
               <p>{{ form.submit(hidden='true', id='form-submit') }}</p>
            </form>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
        
        </div>
    </div>
    </div>
</div>
<script>
    $('#modal-test').click(function(){
        // Perform the action after modal confirm button is clicked.
    
        $('#form-submit').click(); // submitting the form
    });
    </script>
{% if form.errors %}
<script>
$('#deleteModal').modal('show');

</script>

{% endif %}

buckets/templates/budget/deleteall.html
<!-- Delete All Modal -->
<div class="modal fade" id="deleteallModal" tabindex="-1" role="dialog" aria-labelledby="deleteAllModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="deleteAllModalLabel">Delete All</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">Are you sure? Pressing delete all will delete all entries from the table.</div>
        <div class="modal-footer">
            <form action="{{ url_for('routes.deleteall') }}" method="POST">
               <button type="submit" class="btn btn-primary" id="modal-deleteall", value="Delete All">Delete All</button> 
              </form>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
        
        </div>
    </div>
    </div>
</div>
<script>
    $('#modal-deleteall').click(function(){
        // Perform the action after modal confirm button is clicked.
    
        $('#form-submit').click(); // submitting the form
    });
    </script>
{% if form.errors %}
<script>
$('#deleteallModal').modal('show');

</script>

{% endif %}

buckets/templates/budget/index.html

{% extends 'base.html' %}
{% block nav_budget %}active{% endblock %}
{% block header %}
<h1 class="h2">{% block title %}Budget{% endblock %}</h1>  
   
{% endblock %}  

{% block content %}

<div>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#AddNewModal"><svg class="bi bi-plus-circle-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M16 8A8 8 0 110 8a8 8 0 0116 0zM8.5 4a.5.5 0 00-1 0v3.5H4a.5.5 0 000 1h3.5V12a.5.5 0 001 0V8.5H12a.5.5 0 000-1H8.5V4z" clip-rule="evenodd"/>
</svg>  Add New Expense</button>
  {% include "/budget/create.html" %}
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#payModal">Pay Week</button>
  {% include "/budget/payday.html" %}
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteallModal">Delete All</button>
  {% include "/budget/deleteall.html" %}
</div>
{% if form.errors %}
    {{ form.errors }}
{% endif %}
<div class="table-responsive">
  <table id="mainTable" class="table table-striped table-sm" style="width:100%;margin:0px auto" data-toggle="table"  data-show-export="true" data-group-by="true" data-group-by-field="Group">
    <thead>
      <tr>
        {%- for column in columns %}
        <th data-sortable = "{{ column.sortable }}">{{ column.name }}</th>
        {%- endfor %}
        <th data-sortable="false">Add Transaction</th>
      </tr>
    </thead>
    <tbody>
      {% for row in rows %}
      <tr>
        {% for field in fields %}
          <td>{{ row[field] }}</td>
        {% endfor %}
        <td><button type="button" class="btn btn-info btn-sm m-1" data-toggle="modal" data-target="#updateModal{{ row.id }}"><i class="fas fa-edit"></i></button></td>
        {% include "budget/update.html" %}
        <td><button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal{{ row.id }}"><i class="fas fa-trash-alt"></i></button></td>
              <!-- Delete Modal Button-->
        {% include "budget/delete.html" %}
        
        <td><button type="button" class="btn btn-info btn-sm m-1" data-toggle="modal" data-target="#AddTransactModal{{ row.id }}"><i class="fas fa-edit"></i></button></td>
        {% include "budget/transact.html" %}

      {% if not loop.last %}
      <h1>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<script>
  $(function() {
    $('#mainTable').bootstrapTable()
  })
</script>
{% endblock %}

buckets/templates/budget/payday.html
<!-- Pay Day Modal -->
<div class="modal fade" id="payModal" tabindex="-1" role="dialog" aria-labelledby="payModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="payModalLabel">Pay Day</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
        
        </div>
        <div class="modal-footer">
            <form action="{{ url_for('routes.pay_day') }}" method="post">
               <button type="submit" class="btn btn-primary" id="modal-paid", value="payday">Start New Pay Week</button> 
            </form>
            <form action="{{ url_for('routes.cancel_pay') }}" method="post">
                <button type="submit" class="btn btn-primary" id="modal-cancel", value="cancel">Reverse Previous Pay Week</button> 
             </form>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
        
        </div>
    </div>
    </div>
</div>
<script>
    $('#modal-paid').click(function(){
        // Perform the action after modal button is clicked.
    
        $('#form-submit').click(); // submitting the form
    });
    $('#modal-cancel').click(function(){
        // Perform the action after modal button is clicked.
    
        $('#form-submit').click(); // submitting the form
    });
</script>
{% if form.errors %}
<script>
$('#payModal').modal('show');

</script>

{% endif %}

buckets/templates/budget/transact.html
<!-- Add Expense Modal -->
<div class="modal fade" id="AddTransactModal{{ row.id }}" tabindex="-1" role="dialog" aria-labelledby="AddTransactModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="AddTransactModalLabel">Log Transaction</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
        <form action="{{ url_for('transaction.create_trans', transact_flag=transact_flag ) }}" method="post">
            {{ form2.hidden_tag() }}
            <p>
                {{ form2.expense.label }}<br>
                {{ form2.expense(value=row.expense) }}<br>
                {% for error in form2.expense.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form2.amount.label }}<br>
                {{ form2.amount }}<br>
                {% for error in form2.amount.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form2.note.label }}<br>
                {{ form2.note }}<br>
                {% for error in form2.note.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form2.date.label }}<br>
                {{ form2.date(type="date") }}
                {% for error in form2.date.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
                      
            <p>{{ form2.submit(hidden='true', id='form2-submit') }}</p>
        </form2>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
        <button type="submit" class="btn btn-primary" id="modal-create">Log Transaction</button>
        </div>
    </div>
    </div>
</div>
<script>
    $('#modal-create').click(function(){
        // Perform the action after modal confirm button is clicked.
    
        $('#form2-submit').click(); // submitting the form
    });
</script>
{% if form2.errors %}
<script>
$('#AddTransactModal').modal('show');

</script>

{% endif %}

buckets/templates/budget/update.html
<!-- Update Expense Modal -->
<div class="modal fade" id="updateModal{{ row.id }}" tabindex="-1" role="dialog" aria-labelledby="UpdateModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="UpdateModalLabel">Update Expense</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
        <form action="{{ url_for('routes.update_expense', expense_id=row.id) }}" method="post">
            {{ form.hidden_tag() }}
            <p>
                {{ form.group.label }}<br>
                {{ form.group(value=row.group) }}<br>
                {% for error in form.group.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.expense.label }}<br>
                {{ form.expense(value=row.expense) }}<br>
                {% for error in form.expense.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.amount.label }}<br>
                {{ form.amount(value=row.amount) }}<br>
                {% for error in form.amount.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                <label for="avail">Available</label><br>
                <input id="avail" name="avail" required="" type="text" value="{{ row.available}}">

            </p>
            <p>
                {{ form.last_paid.label }}<br>
                {{ form.last_paid(type="date", value=row.last_paid) }}
                {% for error in form.last_paid.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                <label class="mr-sm-2" for="inlineFormCustomSelect">{{ form.cycle.label }}</label>
                <br>

                {{ form.cycle(id="pay_cycle") }}
                <br>
                {% for error in form.cycle.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
                {{ form.nxtlst_select(hidden='true') }}

            <p>{{ form.submit(hidden='true', id='form-update') }}</p>
        </form>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
        <button type="submit" class="btn btn-primary" id="modal-update{{ row.id }}">Update Expense</button>
        </div>
    </div>
    </div>
</div>

<script>
    $('#modal-update{{ row.id }}').click(function(){
        // Perform the action after modal confirm button is clicked.
    
        $('#form-update').click(); // submitting the form
    });
</script>
{% if form.errors %}

{% endif %}